var canvas = document.getElementById("myCanvas");
var map = document.getElementById("myMap");
var ctx = canvas.getContext("2d");
ctx.fillStyle = "white";
ctx.font = "100px Arial";
var ctxM = map.getContext("2d");
ctxM.fillStyle = "white";
ctxM.font = "16px Lucida Console";
var output = document.getElementById("outText");
var input = document.getElementById("inputText");
var tris = [];
var scaleFactor = 300;
var angle = 0;
var resolution = 4;
var resolutionInit = 4;
var pixSize = 2;
var gloabalOffset = [0,0,0];
var objects =[];
const moveSpeed = 0.4;
var inventory = [];
var movesTaken = 0;
var comsDishFixed = false;
var reactorFixed = false;
var mapActive = false;
var activeOBJ = input;
var mapOffset = [0,0,0]
var gameStart = false
var amDead = false;